#!/usr/bin/env node
/**
 * Documentation tracker / linter.
 *
 * Enforces the doc-tracking conventions described in docs/DOCUMENTATION.md:
 *
 *   1. Every doc under docs/ (except the generated index docs/README.md)
 *      carries valid YAML frontmatter: title, status, last_reviewed, owner,
 *      audience, category, summary, related_code.
 *   2. docs/README.md's autogenerated index block lists every doc, grouped by
 *      category. The block is regenerated from frontmatter — run with --write
 *      to update it; without --write a drift is a hard error (so CI catches a
 *      new/renamed doc that nobody added to the index).
 *   3. Relative markdown links in docs and root governance files resolve to a
 *      real file.
 *   4. Staleness: if any related_code path changed (per git) after the doc's
 *      last_reviewed date, warn (does not fail unless --strict).
 *
 * Usage:
 *   node scripts/check-docs.mjs            # validate; non-zero exit on error
 *   node scripts/check-docs.mjs --write    # regenerate the index block in place
 *   node scripts/check-docs.mjs --strict   # treat staleness warnings as errors
 *
 * No external dependencies (hand-rolled frontmatter parser) so it runs in CI
 * without an install step beyond the repo's own toolchain.
 */

import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DOCS_DIR = path.join(REPO_ROOT, "docs");
const INDEX_FILE = path.join(DOCS_DIR, "README.md");
const WRITE = process.argv.includes("--write");
const STRICT = process.argv.includes("--strict");

// Root-level governance/markdown files that are link-checked but exempt from
// frontmatter requirements (they follow GitHub community conventions instead).
const GOVERNANCE_FILES = [
  "README.md",
  "CONTRIBUTING.md",
  "CODE_OF_CONDUCT.md",
  "SECURITY.md",
  "SUPPORT.md",
  "CHANGELOG.md",
];

// Allowed frontmatter enums and the category display order for the index.
const STATUSES = ["stable", "beta", "draft", "deprecated"];
const AUDIENCES = ["contributor", "operator", "user", "all"];
const CATEGORIES = [
  ["getting-started", "Getting started"],
  ["architecture", "Architecture"],
  ["game-design", "Game design"],
  ["api", "API & protocol"],
  ["operations", "Operations"],
  ["features", "User-facing features"],
  ["streamer", "Streamer bot (Pricey)"],
  ["extension", "Browser extension"],
  ["analytics", "Analytics"],
  ["testing", "Testing"],
  ["meta", "Documentation system"],
];
const CATEGORY_KEYS = new Set(CATEGORIES.map(([k]) => k));
const REQUIRED_KEYS = [
  "title",
  "status",
  "last_reviewed",
  "owner",
  "audience",
  "category",
  "summary",
];

const errors = [];
const warnings = [];
const err = (file, msg) => errors.push(`${path.relative(REPO_ROOT, file)}: ${msg}`);
const warn = (file, msg) => warnings.push(`${path.relative(REPO_ROOT, file)}: ${msg}`);

/** Recursively collect *.md files under a directory. */
function walkMarkdown(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walkMarkdown(full));
    else if (entry.isFile() && entry.name.endsWith(".md")) out.push(full);
  }
  return out;
}

/**
 * Parse a leading YAML frontmatter block. Supports scalar `key: value` and
 * block sequences (`key:` then `  - item` lines) — the subset our schema uses.
 * Returns { data, body, hasFrontmatter }.
 */
function parseFrontmatter(raw) {
  if (!raw.startsWith("---\n")) return { data: {}, body: raw, hasFrontmatter: false };
  const end = raw.indexOf("\n---", 4);
  if (end === -1) return { data: {}, body: raw, hasFrontmatter: false };
  const block = raw.slice(4, end);
  const body = raw.slice(raw.indexOf("\n", end + 1) + 1);
  const data = {};
  const lines = block.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!line.trim()) continue;
    const m = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/);
    if (!m) continue;
    const key = m[1];
    let val = m[2].trim();
    if (val === "") {
      // Possible block sequence on following indented "- " lines.
      const arr = [];
      while (i + 1 < lines.length && /^\s+-\s+/.test(lines[i + 1])) {
        arr.push(lines[++i].replace(/^\s+-\s+/, "").trim().replace(/^["']|["']$/g, ""));
      }
      data[key] = arr;
    } else {
      data[key] = val.replace(/^["']|["']$/g, "");
    }
  }
  return { data, body, hasFrontmatter: true };
}

/** Latest committed change date (YYYY-MM-DD) for a path, or null. */
function lastCommitDate(relPath) {
  try {
    const out = execFileSync("git", ["log", "-1", "--format=%cs", "--", relPath], {
      cwd: REPO_ROOT,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    return out || null;
  } catch {
    return null;
  }
}

const isoDate = (s) => typeof s === "string" && /^\d{4}-\d{2}-\d{2}$/.test(s);

// ── 1. Validate frontmatter on every docs/ file ──────────────────────────────
const docFiles = walkMarkdown(DOCS_DIR).filter((f) => f !== INDEX_FILE);
const docMeta = []; // { file, rel, data }

for (const file of docFiles) {
  const raw = fs.readFileSync(file, "utf8");
  const { data, hasFrontmatter } = parseFrontmatter(raw);
  if (!hasFrontmatter) {
    err(file, "missing YAML frontmatter (see docs/DOCUMENTATION.md)");
    continue;
  }
  for (const key of REQUIRED_KEYS) {
    if (data[key] === undefined || data[key] === "") err(file, `frontmatter missing "${key}"`);
  }
  if (data.status && !STATUSES.includes(data.status))
    err(file, `invalid status "${data.status}" (allowed: ${STATUSES.join(", ")})`);
  if (data.audience && !AUDIENCES.includes(data.audience))
    err(file, `invalid audience "${data.audience}" (allowed: ${AUDIENCES.join(", ")})`);
  if (data.category && !CATEGORY_KEYS.has(data.category))
    err(file, `invalid category "${data.category}" (allowed: ${[...CATEGORY_KEYS].join(", ")})`);
  if (data.last_reviewed && !isoDate(data.last_reviewed))
    err(file, `last_reviewed "${data.last_reviewed}" must be YYYY-MM-DD`);
  if (data.related_code && !Array.isArray(data.related_code))
    err(file, `related_code must be a list`);

  // Staleness check against related_code.
  if (isoDate(data.last_reviewed) && Array.isArray(data.related_code)) {
    for (const codePath of data.related_code) {
      const changed = lastCommitDate(codePath);
      if (!changed) {
        // No git history can mean a brand-new (staged, uncommitted) path —
        // only warn if it is also absent from disk.
        if (!fs.existsSync(path.join(REPO_ROOT, codePath)))
          warn(file, `related_code path not found: ${codePath}`);
      } else if (changed > data.last_reviewed) {
        warn(file, `stale: ${codePath} changed ${changed}, after last_reviewed ${data.last_reviewed}`);
      }
    }
  }
  docMeta.push({ file, rel: path.relative(DOCS_DIR, file), data });
}

// ── 2. Index sync (autogenerated block in docs/README.md) ────────────────────
const BEGIN = "<!-- BEGIN AUTOGEN-INDEX -->";
const END = "<!-- END AUTOGEN-INDEX -->";

function buildIndexBlock() {
  const byCat = new Map();
  for (const { rel, data } of docMeta) {
    const cat = CATEGORY_KEYS.has(data.category) ? data.category : "meta";
    if (!byCat.has(cat)) byCat.set(cat, []);
    byCat.get(cat).push({ rel, data });
  }
  const lines = [BEGIN, ""];
  for (const [key, label] of CATEGORIES) {
    const items = byCat.get(key);
    if (!items || items.length === 0) continue;
    items.sort((a, b) => a.rel.localeCompare(b.rel));
    lines.push(`### ${label}`, "");
    lines.push("| Doc | Status | Reviewed | What it covers |", "|---|---|---|---|");
    for (const { rel, data } of items) {
      const title = data.title || rel;
      lines.push(
        `| [${title}](./${rel}) | ${data.status || "?"} | ${data.last_reviewed || "?"} | ${(data.summary || "").replace(/\|/g, "\\|")} |`,
      );
    }
    lines.push("");
  }
  lines.push(END);
  return lines.join("\n");
}

const newBlock = buildIndexBlock();
let indexRaw = fs.existsSync(INDEX_FILE) ? fs.readFileSync(INDEX_FILE, "utf8") : "";
const hasMarkers = indexRaw.includes(BEGIN) && indexRaw.includes(END);

if (!hasMarkers) {
  if (WRITE) {
    // Seed a fresh index file with a hand-editable header above the block.
    const header = `# Documentation\n\nEverything you need to understand, run, contribute to, or operate Price Games.\nThis index is generated from each doc's frontmatter by \`scripts/check-docs.mjs\`;\nedit a doc's frontmatter (not this table) and run \`npm run docs:index\` to refresh.\n\nSee [DOCUMENTATION.md](./DOCUMENTATION.md) for the doc-tracking conventions.\n\n`;
    fs.writeFileSync(INDEX_FILE, header + newBlock + "\n");
    console.log("Created docs/README.md index block.");
  } else {
    err(INDEX_FILE, `missing autogen markers; run "npm run docs:index" to generate the index`);
  }
} else {
  const start = indexRaw.indexOf(BEGIN);
  const finish = indexRaw.indexOf(END) + END.length;
  const current = indexRaw.slice(start, finish);
  if (current.trim() !== newBlock.trim()) {
    if (WRITE) {
      // Splice by offset rather than String.replace — a doc summary containing
      // "$&", "$1", "$$" etc. would be interpreted as a replacement pattern.
      fs.writeFileSync(INDEX_FILE, indexRaw.slice(0, start) + newBlock + indexRaw.slice(finish));
      console.log("Updated docs/README.md index block.");
    } else {
      err(INDEX_FILE, `index out of date; run "npm run docs:index" to regenerate`);
    }
  }
}

// ── 3. Relative-link check across docs + governance files ────────────────────
const LINK_RE = /\]\(([^)]+)\)/g;
const linkTargets = [
  ...walkMarkdown(DOCS_DIR),
  ...GOVERNANCE_FILES.map((f) => path.join(REPO_ROOT, f)).filter((f) => fs.existsSync(f)),
];
for (const file of linkTargets) {
  const raw = fs.readFileSync(file, "utf8");
  for (const m of raw.matchAll(LINK_RE)) {
    let target = m[1].trim();
    if (/^(https?:|mailto:|#|tel:)/i.test(target)) continue; // external / anchor-only
    target = target.split("#")[0].split("?")[0].trim();
    if (!target) continue;
    const resolved = path.resolve(path.dirname(file), target);
    // Links that escape the repo root are GitHub repo-relative (e.g.
    // ../../issues/new/choose) and only resolve on github.com — skip them.
    if (!resolved.startsWith(REPO_ROOT + path.sep)) continue;
    if (!fs.existsSync(resolved)) err(file, `broken relative link: ${m[1]}`);
  }
}

// ── Report ───────────────────────────────────────────────────────────────────
if (warnings.length) {
  console.log(`\n⚠️  ${warnings.length} warning(s):`);
  for (const w of warnings) console.log("  - " + w);
}
if (errors.length) {
  console.log(`\n❌ ${errors.length} error(s):`);
  for (const e of errors) console.log("  - " + e);
}
const failStale = STRICT && warnings.length > 0;
if (errors.length || failStale) {
  console.log(`\nDoc check FAILED.`);
  process.exit(1);
}
console.log(`\n✅ Doc check passed (${docMeta.length} docs indexed${warnings.length ? `, ${warnings.length} warning(s)` : ""}).`);
