import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import JoinScreen from "../components/multiplayer/JoinScreen";
import { makeUser } from "./testUtils";

vi.mock("../api/userClient", () => ({
  userGetMe: vi.fn(),
  userLogin: vi.fn(),
  userLogout: vi.fn(),
  userRegister: vi.fn(),
  userGetOAuthProviders: vi.fn().mockResolvedValue({ google: false, facebook: false }),
}));

import { userGetMe } from "../api/userClient";
const mockGetMe = vi.mocked(userGetMe);

import { UserAuthProvider } from "../context/UserAuthContext";

function renderWithAuth(ui: React.ReactElement) {
  return render(<UserAuthProvider>{ui}</UserAuthProvider>);
}

/**
 * Render variant that includes a router context. Required when the JoinScreen
 * top-strip is enabled (`onLeave` prop set), because the embedded
 * UserDropdown calls `useNavigate()`.
 */
function renderWithRouter(ui: React.ReactElement) {
  return render(
    <MemoryRouter>
      <UserAuthProvider>{ui}</UserAuthProvider>
    </MemoryRouter>,
  );
}

describe("JoinScreen", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockGetMe.mockRejectedValue(new Error("401"));
    // Mock fetch for lobby count
    global.fetch = vi.fn().mockResolvedValue({ ok: true, json: () => Promise.resolve({ lobbies: [] }) });
  });

  const defaultProps = {
    onCreateRoom: vi.fn(),
    onJoinRoom: vi.fn(),
  };

  it("renders hub mode by default (no roomCode)", () => {
    renderWithAuth(<JoinScreen {...defaultProps} />);
    expect(screen.getByText("Multiplayer")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Create Room" })).toBeInTheDocument();
  });

  it("renders join mode when roomCode is provided", () => {
    renderWithAuth(<JoinScreen {...defaultProps} roomCode="ABCD" />);
    expect(screen.getByRole("button", { name: "Join Game" })).toBeInTheDocument();
    // The title also shows "Join Game"
    expect(screen.getAllByText("Join Game")).toHaveLength(2);
  });

  it("falls back to the guest handle when Create Room is clicked with no custom name", () => {
    const onCreateRoom = vi.fn();
    renderWithAuth(<JoinScreen {...defaultProps} onCreateRoom={onCreateRoom} />);
    fireEvent.click(screen.getByRole("button", { name: "Create Room" }));
    expect(onCreateRoom).toHaveBeenCalledTimes(1);
    // Guest handles are two capitalized words separated by a space —
    // generated by the shared guest-identity util.
    const [nameArg] = onCreateRoom.mock.calls[0];
    expect(nameArg).toMatch(/^[A-Z][a-z]+ [A-Z][a-z]+$/);
  });

  it("calls onCreateRoom with trimmed custom name when Create Room is clicked", () => {
    const onCreateRoom = vi.fn();
    renderWithAuth(<JoinScreen {...defaultProps} onCreateRoom={onCreateRoom} />);

    const input = screen.getByLabelText("Display Name (optional)");
    fireEvent.change(input, { target: { value: "  Alice  " } });
    fireEvent.click(screen.getByRole("button", { name: "Create Room" }));

    expect(onCreateRoom).toHaveBeenCalledWith("Alice", "classic", { isPublic: undefined });
  });

  describe("public/private visibility picker", () => {
    it("defaults to Private (isPublic undefined in the create payload)", () => {
      const onCreateRoom = vi.fn();
      renderWithAuth(<JoinScreen {...defaultProps} onCreateRoom={onCreateRoom} />);
      expect(screen.getByRole("radio", { name: /Private/i })).toBeChecked();
      expect(screen.getByRole("radio", { name: /Public/i })).not.toBeChecked();
      fireEvent.click(screen.getByRole("button", { name: "Create Room" }));
      // false || undefined => undefined; payload omits the field.
      expect(onCreateRoom.mock.calls[0][2]).toEqual({ isPublic: undefined });
    });

    it("flipping to Public passes isPublic: true through to onCreateRoom", () => {
      const onCreateRoom = vi.fn();
      renderWithAuth(<JoinScreen {...defaultProps} onCreateRoom={onCreateRoom} />);
      fireEvent.click(screen.getByRole("radio", { name: /Public/i }));
      expect(screen.getByRole("radio", { name: /Public/i })).toBeChecked();
      expect(screen.getByRole("radio", { name: /Private/i })).not.toBeChecked();
      fireEvent.click(screen.getByRole("button", { name: "Create Room" }));
      expect(onCreateRoom.mock.calls[0][2]).toEqual({ isPublic: true });
    });

    it("flipping back to Private clears isPublic in the payload", () => {
      const onCreateRoom = vi.fn();
      renderWithAuth(<JoinScreen {...defaultProps} onCreateRoom={onCreateRoom} />);
      fireEvent.click(screen.getByRole("radio", { name: /Public/i }));
      fireEvent.click(screen.getByRole("radio", { name: /Private/i }));
      fireEvent.click(screen.getByRole("button", { name: "Create Room" }));
      expect(onCreateRoom.mock.calls[0][2]).toEqual({ isPublic: undefined });
    });
  });

  it("calls onJoinRoom with code and name when in join mode", () => {
    const onJoinRoom = vi.fn();
    renderWithAuth(<JoinScreen {...defaultProps} roomCode="WXYZ" onJoinRoom={onJoinRoom} />);

    const input = screen.getByLabelText("Display Name (optional)");
    fireEvent.change(input, { target: { value: "Bob" } });
    fireEvent.submit(input.closest("form")!);

    // The roomCode prop being populated means the user landed on a /<code>
    // URL, which JoinScreen tags as a share-link arrival for analytics.
    expect(onJoinRoom).toHaveBeenCalledWith("WXYZ", "Bob", undefined, "share_link");
  });

  it("shows error message when error prop is set", () => {
    renderWithAuth(<JoinScreen {...defaultProps} error="Room is full" />);
    expect(screen.getByText("Room is full")).toBeInTheDocument();
  });

  it("shows loading state on buttons", () => {
    renderWithAuth(<JoinScreen {...defaultProps} loading />);
    expect(screen.getByRole("button", { name: "Starting..." })).toBeDisabled();
    expect(screen.getByRole("button", { name: "Creating..." })).toBeDisabled();
  });

  it("shows game type selector in hub mode", () => {
    renderWithAuth(<JoinScreen {...defaultProps} />);
    expect(screen.getByText("Game Type")).toBeInTheDocument();
    // Two comboboxes live on the quickplay card now: Game Type and
    // Rounds. Find the one labelled by the "Game Type" label instead of
    // using the generic query so the rounds selector doesn't collide.
    const selects = screen.getAllByRole("combobox");
    expect(selects.length).toBeGreaterThanOrEqual(2);
    // The Game Type select is the first one under the Quick Play card.
    expect(selects[0]).toBeInTheDocument();
  });

  it("shows a rounds selector with random + canonical options on the quickplay card", () => {
    renderWithAuth(<JoinScreen {...defaultProps} />);
    expect(screen.getByText("Rounds")).toBeInTheDocument();
    const selects = screen.getAllByRole("combobox");
    // Second combobox (index 1) is the rounds select; verify the option
    // list includes Random + 3/5/10.
    const roundsSelect = selects[1];
    const optionTexts = Array.from(
      roundsSelect.querySelectorAll("option"),
    ).map((o) => o.textContent);
    expect(optionTexts).toContain("Random");
    expect(optionTexts).toContain("3 rounds");
    expect(optionTexts).toContain("5 rounds");
    expect(optionTexts).toContain("10 rounds");
  });

  it("hides game type selector in join mode", () => {
    renderWithAuth(<JoinScreen {...defaultProps} roomCode="ABCD" />);
    expect(screen.queryByText("Game Type")).not.toBeInTheDocument();
  });

  it("shows room info when joining an existing room", () => {
    renderWithAuth(
      <JoinScreen
        {...defaultProps}
        roomCode="ABCD"
        existingRoom={{
          code: "ABCD",
          gameMode: "classic",
          categories: [],
          hasPassword: false,
          status: "lobby",
          currentRound: 0,
          totalRounds: 10,
          players: [
            { id: "p1", displayName: "Host", avatar: "wizard", isHost: true, isConnected: true, totalScore: 0, isBot: false },
          ],
          hostPlayerId: "p1",
          isPublic: false,
          botCount: 0,
          botDifficulty: "medium",
        }}
      />
    );
    expect(screen.getByText(/1 player waiting/)).toBeInTheDocument();
  });

  it("shows password input when room has password", () => {
    renderWithAuth(
      <JoinScreen
        {...defaultProps}
        roomCode="ABCD"
        existingRoom={{
          code: "ABCD",
          gameMode: "classic",
          categories: [],
          hasPassword: true,
          status: "lobby",
          currentRound: 0,
          totalRounds: 10,
          players: [],
          hostPlayerId: "p1",
          isPublic: false,
          botCount: 0,
          botDifficulty: "medium",
        }}
      />
    );
    expect(screen.getByText("Room Password")).toBeInTheDocument();
    expect(screen.getByPlaceholderText("Enter room password...")).toBeInTheDocument();
  });

  it("falls back to guest handle when the custom-name field is whitespace only", () => {
    const onCreateRoom = vi.fn();
    renderWithAuth(<JoinScreen {...defaultProps} onCreateRoom={onCreateRoom} />);

    fireEvent.change(screen.getByLabelText("Display Name (optional)"), {
      target: { value: "   " },
    });
    fireEvent.click(screen.getByRole("button", { name: "Create Room" }));

    expect(onCreateRoom).toHaveBeenCalledTimes(1);
    const [nameArg] = onCreateRoom.mock.calls[0];
    expect(nameArg).toMatch(/^[A-Z][a-z]+ [A-Z][a-z]+$/);
  });

  it("hides the custom-name input and uses username when logged in", async () => {
    mockGetMe.mockResolvedValue({ user: makeUser({ username: "alice" }) });
    const onCreateRoom = vi.fn();
    renderWithAuth(<JoinScreen {...defaultProps} onCreateRoom={onCreateRoom} />);

    // The IdentityCard in the shared top-bar-wrap shows the username as
    // the identity name once auth resolves.
    await waitFor(() => {
      expect(screen.getByText("alice")).toBeInTheDocument();
    });
    expect(screen.queryByLabelText("Display Name (optional)")).not.toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "Create Room" }));
    expect(onCreateRoom).toHaveBeenCalledWith("alice", "classic", { isPublic: undefined });
  });

  it("shows the optional custom-name input and identity card when logged out", () => {
    renderWithAuth(<JoinScreen {...defaultProps} />);
    expect(screen.getByLabelText("Display Name (optional)")).toBeInTheDocument();
    // IdentityCard renders the anon CTA on every MP screen.
    expect(screen.getByText("Playing as guest")).toBeInTheDocument();
  });

  it("invokes onOpenAuth when the IdentityCard signup CTA is tapped", () => {
    const onOpenAuth = vi.fn();
    renderWithAuth(
      <JoinScreen {...defaultProps} onOpenAuth={onOpenAuth} />,
    );
    fireEvent.click(screen.getByRole("button", { name: /sign up to choose/i }));
    expect(onOpenAuth).toHaveBeenCalledOnce();
  });

  it("opens the lobby browser modal when Browse is clicked", () => {
    renderWithAuth(<JoinScreen {...defaultProps} />);
    const browseBtn = screen.getByRole("button", { name: "Browse" });
    fireEvent.click(browseBtn);
    // Browser now opens as a modal overlay (role=dialog) instead of toggling
    // an inline panel below the cards. The trigger button keeps its "Browse"
    // label; the modal's close affordance is its own × button.
    expect(screen.getByRole("dialog", { name: /browse public games/i })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: /close browser/i })).toBeInTheDocument();
  });

  // ── Layout: 2-on-top, 1-centered-below ─────────────────────
  it("renders the three action cards in a 2+1 grid (Browse Games + Create Room on row 1; Quick Play on row 2)", () => {
    renderWithRouter(<JoinScreen {...defaultProps} onLeave={vi.fn()} />);
    const cards = document.querySelector(".mp-hub-cards");
    expect(cards).toBeInTheDocument();
    // Row 1 (top) wraps the two bonus-bearing cards (Browse + Create)
    const topRow = cards!.querySelector(".mp-hub-cards-row--top");
    expect(topRow).toBeInTheDocument();
    expect(topRow!.querySelector(".mp-hub-card--browse")).toBeInTheDocument();
    expect(topRow!.querySelector(".mp-hub-card--create")).toBeInTheDocument();
    // Row 2 (bottom) wraps Quick Play centered
    const bottomRow = cards!.querySelector(".mp-hub-cards-row--bottom");
    expect(bottomRow).toBeInTheDocument();
    expect(bottomRow!.querySelector(".mp-hub-card--quickplay")).toBeInTheDocument();
  });

  // ── Top-nav cleanup: only the auth pill remains ──────
  it("does not render Leaderboard or Home buttons in the /mp top nav (logo handles home routing)", () => {
    renderWithRouter(<JoinScreen {...defaultProps} onLeave={vi.fn()} />);
    expect(screen.queryByRole("button", { name: "Home" })).not.toBeInTheDocument();
    expect(screen.queryByRole("button", { name: "Leaderboard" })).not.toBeInTheDocument();
  });

  // ── New illustrated icons ─────────────────────────────────
  it("renders new illustrated SVG icons for each action card (sourced from imported assets)", () => {
    renderWithAuth(<JoinScreen {...defaultProps} />);
    // Each card icon container now wraps a single <img> referencing the
    // promoted SVG asset. Vite inlines small SVGs as base64 data URIs in
    // tests, so we assert the icon img exists and has a non-empty src
    // pointing at an SVG asset rather than checking for filename literals.
    const icons = document.querySelectorAll(".mp-hub-card-icon img");
    expect(icons.length).toBe(3);
    icons.forEach((el) => {
      const src = (el as HTMLImageElement).getAttribute("src") ?? "";
      expect(src.length).toBeGreaterThan(0);
      // Either a base64-inlined SVG or a path/URL ending in .svg.
      expect(src).toMatch(/(image\/svg\+xml|\.svg)/);
    });
  });
});
